
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    appname: spring-cloud-eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
