server:
  port: 8080
spring:
  datasource:
    username: root
    password: shijizhuo
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  cache:
    type:
    jcache:
      config: classpath:config/ehcache.xml

  redis:
    jedis:
      pool:
        max-idle: 10   #连接池最大空闲数目
        min-idle: 5    #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        max-wait: -1   #连接池最大阻塞等待时间
    host: localhost
    port: 6379
    timeout: 10000  #连接超时时间（毫秒）
  servlet:
    multipart:
      max-file-size: 200MB #设置单个上传文件的大小
      max-request-size: 200MB #设置一次请求上传文件的总容量
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.shijizhuo.demo.entity

logging:
  level:
    com:
      shijizhuo:
          mapper: debug


